Repository GDG-on-Campus-KHU/iOS-advanced-practice, pull requests merged in 2025-03, with the labels that each got.

#22 [Feat] ScheduleCardView UI
  BBIP-Clone/BBIP-Clone/Assets.xcassets/UserHome/ic_circular_gloves.imageset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/UserHome/ic_circular_gloves.imageset/ic_circular_gloves.svg
  BBIP-Clone/BBIP-Clone/Assets.xcassets/UserHome/ic_circular_keyboard.imageset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/UserHome/ic_circular_keyboard.imageset/ic_circular_keyboard.svg
  BBIP-Clone/BBIP-Clone/Assets.xcassets/UserHome/ic_circular_pen.imageset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/UserHome/ic_circular_pen.imageset/ic_circular_pen.svg
  BBIP-Clone/BBIP-Clone/Presentation/Core/BoardCardView.swift
  BBIP-Clone/BBIP-Clone/Presentation/Core/ScheduleCardView.swift
  BBIP-Clone/BBIP-Clone/Presentation/UserHomeView.swift
Labels: feature

#24 color 구축
  BBIP-Clone/BBIP-Clone/Assets.xcassets/Color/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/Color/accent1.colorset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/Color/accent2.colorset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/Color/accent3.colorset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/Color/gray1.colorset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/Color/gray10.colorset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/Color/gray2.colorset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/Color/gray3.colorset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/Color/gray4.colorset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/Color/gray5.colorset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/Color/gray6.colorset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/Color/gray7.colorset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/Color/gray8.colorset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/Color/gray9.colorset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/Color/mainBlack.colorset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/Color/mainWhite.colorset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/Color/primary1.colorset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/Color/primary2.colorset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/Color/primary3.colorset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/Color/secondary1.colorset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/Color/secondary2.colorset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/Color/secondary3.colorset/Contents.json
  BBIP-Clone/BBIP-Clone/Presentation/StudyHomeView.swift
Labels: resource

#25 [Refactor] 프로퍼티 정의 변경 및 init 추가
  BBIP-Clone/BBIP-Clone/Presentation/Core/ScheduleCardView.swift
Labels: refactor

#28 [Feat]&[Style] TitleView, TitleButtonView 속성 수정
  BBIP-Clone/BBIP-Clone/Presentation/Core/TitleButtonView.swift
  BBIP-Clone/BBIP-Clone/Presentation/Core/TitleView.swift
Labels: refactor, feature

#27 캡슐뷰3타입
  BBIP-Clone/BBIP-Clone/Presentation/Core/CapsuleView.swift
Labels: style

#31 studylistview 완성
  BBIP-Clone/BBIP-Clone/Assets.xcassets/StudyHome/Ellipse 16.imageset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/StudyHome/Ellipse 16.imageset/Ellipse 16.png
  BBIP-Clone/BBIP-Clone/Presentation/Core/StudyListView.swift
Labels: feature

#33 [Feat] MemberCardView UI
  BBIP-Clone/BBIP-Clone/Assets.xcassets/StudyHome/2dubu.imageset/2dubu.png
  BBIP-Clone/BBIP-Clone/Assets.xcassets/StudyHome/2dubu.imageset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/StudyHome/Gardeniaa101.imageset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/StudyHome/Gardeniaa101.imageset/Gardeniaa101.jpeg
  BBIP-Clone/BBIP-Clone/Assets.xcassets/StudyHome/binschocolate.imageset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/StudyHome/binschocolate.imageset/binschocolate.png
  BBIP-Clone/BBIP-Clone/Assets.xcassets/StudyHome/ic_circular_plus.imageset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/StudyHome/ic_circular_plus.imageset/ic_plus.svg
  BBIP-Clone/BBIP-Clone/Presentation/Core/BoardCardView.swift
  BBIP-Clone/BBIP-Clone/Presentation/Core/MemberCardView.swift
  BBIP-Clone/BBIP-Clone/Presentation/Core/ScheduleCardView.swift
  BBIP-Clone/BBIP-Clone/Presentation/StudyHomeView.swift
  BBIP-Clone/BBIP-Clone/Presentation/UserHomeView.swift
Labels: feature

#35 [bug fix] 빌드 오류 해결
  BBIP-Clone/BBIP-Clone/Assets.xcassets/abc.appiconset/Contents.json
Labels: bug

#39 [bug fix] 타입 추론 오류 해결
  BBIP-Clone/BBIP-Clone/Assets.xcassets/StudyHome/img_ring.imageset/Contents.json
  BBIP-Clone/BBIP-Clone/Assets.xcassets/StudyHome/img_ring.imageset/img_ring.png
  BBIP-Clone/BBIP-Clone/Assets.xcassets/StudyHome/img_ring.imageset/img_ring.svg
  BBIP-Clone/BBIP-Clone/Presentation/Core/NoticeView.swift
  BBIP-Clone/BBIP-Clone/Presentation/Core/ProgressBarView.swift
  BBIP-Clone/BBIP-Clone/Presentation/Core/StudyDetailView.swift
  BBIP-Clone/BBIP-Clone/Presentation/Core/StudyListView.swift
  BBIP-Clone/BBIP-Clone/Presentation/Core/StudyProgressBarView.swift
  BBIP-Clone/BBIP-Clone/Presentation/Core/TitleButtonView.swift
  BBIP-Clone/BBIP-Clone/Presentation/Core/TitleView.swift
  BBIP-Clone/BBIP-Clone/Presentation/StudyHomeView.swift
  BBIP-Clone/BBIP-Clone/Presentation/UserHomeView.swift
Labels: bug
